tigerProxy:
  name: remote-tiger-proxy
  proxyPort: 9090
  adminPort: 8080
  additionalProxyPorts:
    - 8081
    - 8443
    - 443
    - 80
  forwardToProxy:
    hostname: ti-connect-tiger-proxy
    port: 9090
    noProxyHosts:
      - popp-client
      - vsdm-client
      - card-terminal-client
  tls:
    serverRootCa: "tigerProxy.p12"
#    masterSecretsFile: /tmp/secrets.txt
    alternativeNames:
        - "popp-ingress"
        - "vsdm-zeta-ingress"
  activateRbelParsingFor:
    - websocket
  proxyRoutes:
    - from: /
      to: http://popp-client:8081/
      matchForProxyType: false
      hosts:
        - "popp-client"
  rewriteHostHeader: false
  honorHostHeaderRouting: true
