location /CertData. {
    asl on;
    pep off;

    satisfy all;
    allow all;
}

location /ASL {
    pep on;
    asl on;
    pep_require_popp off;

    client_body_buffer_size 1m;
    client_max_body_size 1m;

    satisfy all;
    allow all;
}
