# for websockets
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      '';
}
proxy_read_timeout 300s;

# A_26920: ZETA/ASL mindestens HTTP-Version 1.1
map $server_protocol $reject_proto {
    "HTTP/1.1" 0; # fast-path
    "HTTP/2.0" 0;
    ~*^HTTP/1\.1$ 0; # case-insensitive
    ~*^HTTP/2\.0$ 0;
    default 1; # reject everything else
}

default_type application/octet-stream;

log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                '$status $body_bytes_sent ${request_time}s (${upstream_connect_time},${upstream_header_time},${upstream_response_time}) "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for"';

sendfile on;
aio threads;
aio_write on;
tcp_nopush on;

log_subrequest on;

reset_timedout_connection on;
