worker_processes  auto;

load_module modules/libngx_pep.so;

error_log  /dev/stdout debug;
pid        /tmp/nginx.pid;


events {
    worker_connections 1024;
    multi_accept       on;
    use                epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /dev/stdout  main;

    sendfile    on;
    aio         threads;
    aio_write   on;
    tcp_nopush  on;

    keepalive_timeout  65;

    gzip  on;

    pep_pdp_issuer https://vsdm-zeta-ingress/auth/realms/zeta-guard;
    pep_http_client_accept_invalid_certs on;
    pep_require_popp    on;
    pep_popp_issuer http://popp-token-generator/;

    pep_asl_testing     on;
    pep_asl_ca_cert     /etc/nginx/asl/issuer_cert.pem;
    pep_asl_root_ca     FAKE.RCA1;
    pep_asl_roots_json  /etc/nginx/asl/roots.json;
    pep_asl_signer_cert /etc/nginx/asl/signer_cert.pem;
    pep_asl_signer_key  /etc/nginx/asl/signer_key.pem;

    server {
        listen      80;
        server_name vsdm-zeta-pep;

        location / {
            proxy_pass http://vsdm-server:80/;
            pep        on;
        }

        location /ASL {
            # PoPP token is send along in ASL channel and not as a regular
            # header
            pep_require_popp off;
            pep              on;
            asl              on;
        }

        location = /.well-known/oauth-authorization-server {
            proxy_pass         http://vsdm-zeta-pdp/auth/realms/zeta-guard/.well-known/zeta-guard-well-known;
            proxy_http_version 1.1;
        }

        location /.well-known/ {
            default_type  application/json;
            alias         /srv/.well-known/;
            autoindex     off;
        }
    }
}
