tigerProxy:
  name: ti-connect-tiger-proxy
  proxyPort: 9090
  adminPort: 8080
  additionalProxyPorts:
    - 8443
    - 443
    - 80
  # if you want to forward the traffic to another proxy you can configure the forwarding proxy here.
  #  forwardToProxy:
  #    hostname: 192.168.110.10
  #    port: 3128
  #    noProxyHosts:
  #      - 127.0.0.1
  #      - localhost
  #      - popp-client
  #      - vsdm-client
  #      - card-terminal-client
  #      - vsdm-zeta-ingress
  #      - popp-zeta-ingress
  tls:
    serverRootCa: "tigerProxy.p12"
#    masterSecretsFile: /tmp/secrets.txt
  activateRbelParsingFor:
    - websocket
  rewriteHostHeader: false
  honorHostHeaderRouting: true
logging:
  level:
    ROOT: INFO
    de.gematik: DEBUG
