name: "testhub-backend"

include:
  - ./compose-popp-services.yaml
  - ./compose-vsdm-services.yaml

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    env_file:
      - path: ../.env
        required: true
    profiles: [ "full" ]
    platform: linux/amd64
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "${PORT_OTEL_COLLECTOR:?PORT_OTEL_COLLECTOR missing – set it in doc/docker/.env}:4318"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    env_file:
      - path: ../.env
        required: true
    profiles: [ "full", "backend-only" ]
    platform: linux/amd64
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "${PORT_PROMETHEUS:?PORT_PROMETHEUS missing – set it in doc/docker/.env}:7100"
    command:
      - '--config.file=/etc/prometheus/config.yaml'
      - '--web.listen-address=:7100'

  grafana:
    image: grafana/grafana
    env_file:
      - path: ../.env
        required: true
    profiles: [ "full", "backend-only" ]
    platform: linux/amd64
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_PASSWORD_MUST_CHANGE=false
    ports:
      - "${PORT_GRAFANA:?PORT_GRAFANA missing – set it in doc/docker/.env}:3000"
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  default:
    name: testhub_backend

