services:
  popp-token-generator:
    container_name: popp-token-generator
    platform: linux/amd64
    image: gematik1/popp-token-generator:1.0.12
    env_file:
      - path: ../.env
        required: true
    ports:
      - "${PORT_POPP_TOKEN_GENERATOR:?PORT_POPP_TOKEN_GENERATOR missing – set it in doc/docker/.env}:80"
    environment:
      - SPRING_PROFILES_ACTIVE=beispielimpl
    networks:
      - testhub_backend

  popp-client:
    profiles: [ "full" ]
    image: gematik1/popp-client:2.4.1
    env_file:
      - path: ../.env
        required: true
    platform: linux/amd64
    container_name: popp-client
    environment:
      - SPRING_PROFILES_ACTIVE=dev-local
      - ZETA_AUTHENTICATION_SMB_KEYFILE=/app/smcb_private.p12
      - POPP_SERVER_URL=wss://popp-zeta-ingress:443/ws
      # URL für echten POPP-Server:
      #      - POPP_SERVER_URL=wss://popp.dev.poppservice.de/popp/practitioner/api/v1/token-generation-ehc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      #      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5013"
      - VIRTUAL_CARD_IMAGE_FILE=/data/cards/egkCardImage.xml
    networks:
      - testhub_client
    ports:
      - "${PORT_POPP_CLIENT:?PORT_POPP_CLIENT missing – set it in doc/docker/.env}:8081"
      - "${PORT_POPP_CLIENT_MGMT:?PORT_POPP_CLIENT_MGMT missing – set it in doc/docker/.env}:9001"
    volumes:
      - ./zeta/smcb-private/smcb_private.p12:/app/smcb_private.p12:ro
      - ../../../test/vsdm-testsuite/src/test/resources/data/cards:/data/cards:ro
    depends_on:
      - popp-server
      - otel-collector

  popp-server:
    profiles: [ "full" ]
    image: gematik1/popp-server:2.4.1
    env_file:
      - path: ../.env
        required: true
    platform: linux/amd64
    container_name: popp-server
    ports:
      - "${PORT_POPP_SERVER:?PORT_POPP_SERVER missing – set it in doc/docker/.env}:8443"
    environment:
      - IDENTITIES_LOCATION=classpath:identities
      - CERT_HASH_IMPORT_LOCATION=file:/app/import
      - SPRING_DATASOURCE_URL=jdbc:postgresql://popp-server-db:5432/egk_hash_db
    networks:
      - testhub_backend
    depends_on:
      - popp-server-db
      - otel-collector

  popp-server-db:
    profiles: [ "full" ]
    image: postgres:18-alpine
    env_file:
      - path: ../.env
        required: true
    platform: linux/amd64
    container_name: popp-server-db
    environment:
      POSTGRES_USER: poppserver
      POSTGRES_PASSWORD: verysafe
      POSTGRES_DB: egk_hash_db
    ports:
      - "${PORT_POPP_SERVER_DB:?PORT_POPP_SERVER_DB missing – set it in doc/docker/.env}:5432"
    tmpfs:
      - /var/lib/postgresql
    restart: on-failure
    networks:
      - testhub_backend

  popp-zeta-ingress:
    profiles: [ "full" ]
    container_name: popp-zeta-ingress
    platform: linux/amd64
    image: "nginx:1.29.7"
    env_file:
      - path: ../.env
        required: true
    ports:
      - "${PORT_POPP_ZETA_INGRESS:?PORT_POPP_ZETA_INGRESS missing – set it in doc/docker/.env}:443"
    volumes:
      - ./zeta-popp/ingress/conf:/etc/nginx/conf.d:ro
      - ./zeta-popp/ingress/certs:/etc/nginx/certs:ro
    networks:
      - testhub_backend
    depends_on:
      - popp-zeta-pep

  popp-zeta-pep:
    profiles: [ "full" ]
    image: europe-west3-docker.pkg.dev/gematik-pt-zeta-prod/zeta-dcr/ngx_pep:1.0.1
    env_file:
      - path: ../.env
        required: true
    platform: linux/amd64
    environment:
      - POPP_SERVER_HOST=popp-server:8443
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - ALL_PROXY=
      - http_proxy=
      - https_proxy=
      - all_proxy=
      - NO_PROXY=localhost,127.0.0.1,popp-zeta-ingress,popp-zeta-pep,popp-zeta-pdp,popp-zeta-pdp-opa,popp-server
      - no_proxy=localhost,127.0.0.1,popp-zeta-ingress,popp-zeta-pep,popp-zeta-pdp,popp-zeta-pdp-opa,popp-server
    ports:
      - "${PORT_POPP_ZETA_PEP:?PORT_POPP_ZETA_PEP missing – set it in doc/docker/.env}:80"
    volumes:
      - ./zeta-popp/pep/conf/:/etc/nginx/templates/:ro
      - ./zeta-popp/pep/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./zeta-popp/well-known/oauth-protected-resource:/srv/.well-known/oauth-protected-resource:ro
    networks:
      - testhub_backend
    depends_on:
      popp-zeta-pdp:
        condition: service_healthy
      popp-server:
        condition: service_started # TODO: change to "service_healthy" when healthcheck is available

  popp-zeta-pdp:
    profiles: [ "full" ]
    image: europe-west3-docker.pkg.dev/gematik-pt-zeta-prod/zeta-dcr/keycloak-zeta:1.0.1
    env_file:
      - path: ../.env
        required: true
    platform: linux/amd64
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      GENESIS_HASH: "4841c2142fef441daa6ee6c57db65c011935964b14e94a6c8f5ec0447b83526c"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://popp-zeta-pdp-db:5432/keycloak?sslmode=disable"
      KC_DB_USERNAME: "keycloak_db_user"
      KC_DB_PASSWORD: "keycloak_db_user_password"
      KC_DB_SCHEMA: "public"
      SMCB_HASHING_PEPPER: "-085c1245-dc0d-4d39-95b4-97496bec6182"
      TPM_KEYSTORE_LOCATION: /opt/keycloak/conf/tpm/tpm-certificates.p12
      TPM_KEYSTORE_PASSWORD: "O3Bdel9P5+cOgzIGANkOPEzBQM3V"
      KC_HTTP_PORT: 80
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME: https://popp-zeta-ingress/auth/
      PROXY_ADDRESS_FORWARDING: true
      KC_HEALTH_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY_HEADERS: xforwarded
      KC_LOG_LEVEL: INFO
      SMCB_KEYSTORE_LOCATION: /opt/keycloak/conf/smcb/truststore.p12
      SMCB_KEYSTORE_PASSWORD: "changeit"
      KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_OPA_ENABLED: true
      KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_OPA_BASE_URL: http://popp-zeta-pdp-opa:8181
      KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_DECISION_PATH: "/v1/data/zeta/authz/decision"
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      http_proxy: ""
      https_proxy: ""
      all_proxy: ""
      NO_PROXY: "localhost,127.0.0.1,popp-zeta-ingress,popp-zeta-pep,popp-zeta-pdp,popp-zeta-pdp-opa,popp-server"
      no_proxy: "localhost,127.0.0.1,popp-zeta-ingress,popp-zeta-pep,popp-zeta-pdp,popp-zeta-pdp-opa,popp-server"
      DEBUG: "true"
      DEBUG_PORT: "*:5022"
    ports:
      - "${PORT_POPP_ZETA_PDP:?PORT_POPP_ZETA_PDP missing – set it in doc/docker/.env}:80"
      - "${PORT_POPP_ZETA_PDP_HEALTH:?PORT_POPP_ZETA_PDP_HEALTH missing – set it in doc/docker/.env}:9000"
      - "${PORT_POPP_ZETA_PDP_DEBUG:?PORT_POPP_ZETA_PDP_DEBUG missing – set it in doc/docker/.env}:5022"
    volumes:
      - ./zeta-popp/realm:/opt/keycloak/data/import
      - ./zeta-popp/smcb:/opt/keycloak/conf/smcb
      - ./zeta/tpm/:/opt/keycloak/conf/tpm
    networks:
      - testhub_backend
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e \"GET /auth/health/live HTTP/1.1\r\nhost: localhost:9000\r\nConnection: close\r\n\r\n\" >&3;grep \"status.*UP\" <&3" ]
      start_period: 120s
      interval: 5s
      timeout: 5s
      retries: 30
    command: [ "start-dev","--import-realm" ]
    depends_on:
      - popp-zeta-pdp-db

  popp-zeta-pdp-db:
    profiles: [ "full" ]
    container_name: popp-zeta-pdp-db
    platform: linux/amd64
    image: postgres:16.2
    env_file:
      - path: ../.env
        required: true
    ports:
      - "${PORT_POPP_ZETA_PDP_DB:?PORT_POPP_ZETA_PDP_DB missing – set it in doc/docker/.env}:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - testhub_backend
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: keycloak_db_user_password
      # POSTGRES_DB: test1
      # POSTGRES_USER: testuser1
      # POSTGRES_PASSWORD: parr

  popp-zeta-pdp-opa:
    profiles: [ "full" ]
    container_name: popp-zeta-pdp-opa
    image: europe-west3-docker.pkg.dev/gematik-pt-zeta-prod/zeta-dcr/opa:1.14.1-static
    env_file:
      - path: ../.env
        required: true
    platform: linux/amd64
    environment:
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      http_proxy: ""
      https_proxy: ""
      all_proxy: ""
      NO_PROXY: "localhost,127.0.0.1,popp-zeta-pdp-opa,popp-zeta-pdp"
      no_proxy: "localhost,127.0.0.1,popp-zeta-pdp-opa,popp-zeta-pdp"
    ports:
      - "${PORT_POPP_ZETA_PDP_OPA:?PORT_POPP_ZETA_PDP_OPA missing – set it in doc/docker/.env}:8181"
    command:
      - 'run'
      - '--server'
      - '--log-level=debug'
      - '--addr=0.0.0.0:8181'
      - '/policies/authz.rego'
    volumes:
      - ./zeta-popp/policies/authz.rego:/policies/authz.rego:ro
    networks:
      - testhub_backend

