app.version: 0.0.1-dev
server:
  error:
    whitelabel.enabled: false
    include-message: always
  port: ${SERVER_PORT:80}

vsdm:
  path-to-test-data: ${VSDM_PATH_TO_TEST_DATA:./public-test-data}
  iknr: 109500969
  valid-kvnr-prefix: X1
  invalid-kvnr-prefix: X4
  unknown-kvnr-prefix: X9
  valid-profile-version-mapping:
    1.0: 1.0.0

